#minio配置
minio:
   # bucket名称
   bucket: school
  # Minio服务地址
  #minio.host= http://172.18.23.133:9001
   host: http://172.21.255.138:9001
   port: 9001
  # 访问路径
  #minio.url=  ${minio.host}/${minio.bucket}/
   url:  /${minio.bucket}/
  # MINIO_ACCESS_KEY
   access-key: 110120119
  # MINIO_SECRET_KEY
   secret-key: 110120119
# 配置端口
server:
   port: 8090
spring:
   profiles: dev
#   上传文件总的最大值
   servlet:
      connectionTimeout: 180000
      multipart:
        max-request-size: 100MB
        max-file-size: 100MB
#   redis:
#      host: 127.0.0.1
#      port: 6379
#      database: 0
#      password: root
   devtools:
      restart:
         enabled: true #设置开启热部署
         additional-paths: src/main/java #重启目录
         exclude: static/**
#开启热部署
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/school_life?serverTimezone=GMT%2B8&useSSL=false
      username: school
      password: school
# 配置数据源
      type: com.alibaba.druid.pool.DruidDataSource
      hikari:
         connection-test-query: SELECT 1
         minimum-idle: 10
         maximum-pool-size: 100
         connection-timeout: 14400000 #设置开启热部署
# hikari
      hibernate: #重启目录
         ddl-auto: none
      properties:
         hibernate:
            enable_lazy_load_no_trans: true
# hibernate
#jwt
jwt:
   # 令牌前缀
   header: Authorization
# properties
   token-start-with: Bearer
   base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
   token-validity-in-seconds: 14400000
#mybatis:
#   mapper-locations: classpath:mapping/*Mapper.xml
#   type-aliases-package: com.example.entity
mybatis-plus:
   #实体扫描，多个package用逗号或者分号分隔
   type-aliases-package: net.mw.school.pojo.po
   configuration:
      #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
      map-underscore-to-camel-case: true
      cache-enabled: false
      #当查询数据为空时字段返回为null，不加这个查询数据为空时，字段将被隐藏
      call-setters-on-nulls: true
      auto-mapping-behavior: full
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
   global-config:
      # 逻辑删除配置
      db-config:
         #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
        # id-type: id_worker
         #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
        # field-strategy: not_empty
         # 删除前
         logic-not-delete-value: 1
         # 删除后
         logic-delete-value: 0
# 使用Base64对该令牌进行编码
pagehelper:
#(制定您的密钥)
# 令牌过期时间 此处单位/毫秒
   helperDialect: mysql
   reasonable: true
   supportMethodsArguments: true
   params: count=countSql
logging:
   file: mylogfile.log
   path: logs
   level:
      net:
         mw: debu
   pattern:
      file: '%d{yyyy年-MM月-dd日 HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
      console: '%d{yyyy年-MM月-dd日 HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
# ----------------
# Orphan comments:
# ----------------
# Was at begin of line:69 :#showSql